pipeline:
  name: cicd-pipeline
  identifier: Build_ravi3284_simple_maven_java_app_1747764146442
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubconnector
        build: <+input>
  stages:
    - stage:
        name: ci-stage
        identifier: cistage
        template:
          templateRef: CItemplate
          versionLabel: 1.0.0
          templateInputs:
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: trivy_image_scan
                      template:
                        templateInputs:
                          identifier: trivy_image_scan
                          type: Run
                          envirnomentVariables:
                            - name: TRIVY_IMAGE
                              type: String
                              value: <+input>
    - stage:
        name: deploy to dev
        identifier: build_ravi3284_simple_maven_java_app_1747764146442
        tags: {}
        template:
          templateRef: rolloutdeployjavacluster
          versionLabel: 1.0.0
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: <+pipeline.variables.serviceRef>
              environment:
                environmentRef: <+pipeline.variables.environmentRef>
                infrastructureDefinitions:
                  - identifier: <+pipeline.variables.infraIdentifier>
  variables:
    - name: TRIVY_IMAGE
      type: String
      value: ravi3284/simple-maven-java-app:latest
    - name: imageRepo
      type: String
      description: ""
      required: false
      value: ravi3284/simple-maven-java-app
    - name: imageTag
      type: String
      description: ""
      required: false
      value: latest
    - name: serviceRef
      type: String
      value: java_app
    - name: environmentRef
      type: String
      value: dev_k3d
    - name: infraIdentifier
      type: String
      value: k3d_infra
     
      
