pipeline:
  name: cicd-pipeline
  identifier: Build_ravi3284_simple_maven_java_app_1747764146442
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubconnector
        build: <+input>
  stages:
    - stage:
        name: ci-stage
        identifier: cistage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Owasp
                  name: Run OWASP Scan
                  identifier: Run_OWASP_Scan
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      workspace: .
                      name: simple-maven-java-app
                      variant: main
                    advanced:
                      log:
                        level: info
                      fail_on_severity: none
              - step:
                  type: Run
                  name: Maven Build
                  identifier: maven_build
                  spec:
                    shell: Bash
                    command: |
                      mvn clean package
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry
                  spec:
                    connectorRef: docker_connector
                    repo: <+pipeline.variables.imageRepo>
                    tags:
                      - <+pipeline.variables.imageTag>
                    dockerfile: Dockerfile
                    context: .
              - step:
                  type: Run
                  name: Trivy Image Scan
                  identifier: trivy_image_scan
                  spec:
                    shell: Bash
                    command: |
                      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
                      trivy image --exit-code 1 --severity HIGH,CRITICAL ravi3284/simple-maven-java-app:latest
    - stage:
        name: deploy to dev
        identifier: build_ravi3284_simple_maven_java_app_1747764146442
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: java_app
          environment:
            environmentRef: dev_k3d
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k3d_infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: imageRepo
      type: String
      description: ""
      required: false
      value: ravi3284/simple-maven-java-app
    - name: imageTag
      type: String
      description: ""
      required: false
      value: latest
